#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# scripts/ nằm trong apps/mobile — mọi lệnh eas/expo bên dưới cần chạy từ root
# project Expo (apps/mobile), không phải từ nơi gọi script.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

TOTAL_STAGES=7

banner "EAS dev client — build cài lên iPhone thật (thay Expo Go, ADR-0018)"

# ── Stage 1: đăng nhập Expo ─────────────────────────────────────────────
stage "Đăng nhập tài khoản Expo"
say "EAS Build chạy trên cloud của Expo — cần 1 tài khoản expo.dev (miễn phí)."
if ! confirm "Bạn đã có tài khoản expo.dev chưa?"; then
  open_url "https://expo.dev/signup"
  pause "Tạo tài khoản xong thì Enter để tiếp tục."
fi
step "Chạy lệnh dưới, đăng nhập bằng tài khoản Expo (email/password hoặc mã gửi qua email):"
npx eas-cli login
npx eas-cli whoami
note "Đăng nhập thành công — eas-cli sẽ nhớ phiên đăng nhập cho các lệnh sau."

# ── Stage 2: liên kết project với EAS ───────────────────────────────────
stage "Liên kết project này với EAS"
say "Tạo (hoặc gắn) 1 EAS project cho app — ghi projectId vào apps/mobile/app.json (extra.eas.projectId)."
npx eas-cli init
note "Nếu app.json vừa bị sửa (thêm extra.eas.projectId) — nhớ commit lại sau khi xong wizard này."

# ── Stage 3: kiểm tra Apple Developer Program ───────────────────────────
stage "Apple Developer Program (bắt buộc để cài lên iPhone thật)"
warn "Apple CHỈ cho cài app build riêng (không qua App Store) lên thiết bị thật nếu tài khoản Apple ID"
warn "đã đăng ký Apple Developer Program — trả phí 99 USD/năm, có thể mất 24-48h để được duyệt."
if ! confirm "Apple ID của bạn đã có Apple Developer Program (trả phí) chưa?"; then
  open_url "https://developer.apple.com/programs/enroll/"
  step "Đăng ký xong (có thể mất 1-2 ngày để Apple duyệt) rồi quay lại chạy tiếp script này."
  warn "Không có Developer Program thì KHÔNG cài được lên iPhone thật — chỉ build được cho Simulator"
  warn "(Simulator không có camera/Face ID thật, không test được đúng tính năng cần test)."
  if ! confirm "Đã đăng ký xong, Apple đã duyệt, muốn tiếp tục ngay bây giờ?"; then
    say "Dừng ở đây — chạy lại script này (bash scripts/eas-dev-client-setup.sh) khi đã có Developer Program."
    exit 0
  fi
fi

# ── Stage 4: đăng ký UDID iPhone ────────────────────────────────────────
stage "Đăng ký iPhone của bạn với Apple (UDID)"
say "EAS cần biết UDID máy bạn để Apple cấp phép cài app build riêng (ad hoc) lên đúng máy đó."
step "Lệnh dưới sẽ in ra 1 link/QR — mở Safari TRÊN CHÍNH IPHONE (không phải máy tính) rồi quét/mở link đó."
npx eas-cli device:create
pause "Quét xong trên iPhone, thấy trang xác nhận đã đăng ký thiết bị thì Enter để tiếp tục."

# ── Stage 5: build dev client ───────────────────────────────────────────
stage "Build dev client (chạy trên cloud EAS, ~10-20 phút)"
say "Lần đầu build, EAS sẽ hỏi có muốn EAS TỰ quản lý Apple credentials không (đăng nhập Apple ID,"
say "tạo provisioning profile/certificate) — chọn Yes/để EAS lo, đơn giản hơn tự làm tay nhiều."
npx eas-cli build --profile development --platform ios
note "Build xong, EAS in ra link tải + QR cài đặt — giữ terminal này, dùng luôn ở bước sau."

# ── Stage 6: cài lên iPhone ──────────────────────────────────────────────
stage "Cài app build vừa xong lên iPhone"
step "Mở Safari TRÊN IPHONE, quét QR (hoặc mở link) mà lệnh build ở trên vừa in ra."
step "Bấm \"Install\" trên trang đó."
step "Cài xong: Settings → General → VPN & Device Management → chọn profile developer vừa cài → Trust."
pause "Cài + Trust xong thì Enter để tiếp tục."

# ── Stage 7: chạy dev server & kết nối ──────────────────────────────────
stage "Chạy dev server, mở app trên iPhone"
say "Mở app vừa cài (icon riêng, khác Expo Go) trên iPhone."
say "Ở máy tính, chạy lệnh dưới rồi quét QR hiện ra bằng app vừa cài (không phải Expo Go nữa)."
note "Lệnh: npx expo start --dev-client  (chạy trong apps/mobile)"
note "Giờ test được đúng tính năng cần thiết bị thật: Face ID/vân tay (features/auth/store.ts),"
note "camera chụp phiếu OCR (features/ocr-capture), share sheet xuất Excel/PDF (features/reports)."
# ──────────────────────────────────────────────────────────────────────────

finish
